### ISSUE TITLE
null is not an object (evaluating '_reactNativeNfcCardReader.default.startNfc')

### ISSUE THREAD

**Issue by harnie2275** [jackbayliss/react-native-nfc-card-reader#11]
Hello, I have been getting this error. Here is my AndroidManifest.xml

<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.uhpay">

  .... Other codes
  <uses-permission android:name="android.permission.NFC" />

  <application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round" android:allowBackup="false" android:theme="@style/AppTheme">
    <activity android:name=".MainActivity" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" android:launchMode="singleTask" android:windowSoftInputMode="adjustResize">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>
    <activity android:name="com.jackbayliss.nfcreader.NfcCardReaderActivity">
      <intent-filter>
        <action android:name="android.nfc.action.TECH_DISCOVERED" />
        <category android:name="android.intent.category.DEFAULT" />
      </intent-filter>
    </activity>
  </application>
</manifest>

**Comment by jackbayliss** [comment]
@harnie2275  Seems to be an issue with auto-linking I believe, perhaps try `cd android && ./gradlew clean`

The project is somewhat now outdated, as the library I used doesn't exist in Mavern anymore. When I get the chance I'll try and update it :)

**Comment by jackbayliss** [comment]
I've just updated the project, you will need to add the activity like in the demo : [here](https://github.com/jackbayliss/react-native-nfc-card-reader-sample/blob/master/android/app/src/main/AndroidManifest.xml)
