### ISSUE TITLE
Support Gradle 7.0

### ISSUE THREAD

**Issue by dennispost99** [jackbayliss/react-native-nfc-card-reader#14]
Hello,

I get the following build errors when I try to build with gradle 7.2.

```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'D:\repos\orderjay-business\node_modules\react-native-nfc-card-reader\android\build.gradle' line: 23

* What went wrong:
A problem occurred evaluating project ':react-native-nfc-card-reader'.
> Plugin with id 'maven' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get 
full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-nfc-card-reader'.
> com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get 
full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 16s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
```

My gradle-wrapper.properties
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-all.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

These erros seem to be related to the replacement of the maven plugin with maven-publish.
This is also mentioned on the gradle website https://docs.gradle.org/7.0/userguide/upgrading_version_6.html#removal_of_the_legacy_maven_plugin.

I tried to get it to work by changing the plugin names locally, but that only resulted in other erros.

Can someone who has more experience with gradle take a look?

**Comment by jackbayliss** [comment]
@dennispost99  I believe it's a case of changing: 
`apply plugin: 'maven'` to `apply plugin: 'maven-publish`

I'm not sure how to handle multiple Gradle versions, though I can create a new branch for Gradle 7

**Comment by jackbayliss** [comment]
@dennispost99 For Gradle 7.0 you can now do : 
 `npm install "https://github.com/jackbayliss/react-native-nfc-card-reader.git#gradle7.0" --save`

**Comment by VictorOdede** [comment]
> @dennispost99 For Gradle 7.0 you can now do : `npm install "https://github.com/jackbayliss/react-native-nfc-card-reader.git#gradle7.0" --save`


I had same problem using Gradle 7.2 with `compileSDK=30`. This solution alone did not work for me. In addition to this I edited the `build.gradle` file within the package folder to add:
 `configurations {
  customConfig.extendsFrom implementation
}`

then add this in the `afterEvaluate` function: 
`tasks.withType(Javadoc) {
      failOnError false
      options.addStringOption('Xdoclint:none', '-quiet')
      options.addStringOption('encoding', 'UTF-8')
      options.addStringOption('charSet', 'UTF-8')
}`

then replace `classpath += files(project.getConfigurations().getByName('compile').asList())` with `classpath += files(project.getConfigurations().getByName('customConfig').asList())`: 

You need to also add this line to `AndroidManifest.xml`: 
    `<activity 
        android:name="com.jackbayliss.nfcreader.NfcCardReaderActivity"
        android:label="Preferences" >
      </activity>`

**Comment by jackbayliss** [comment]
@VictorOdede  Thanks for your feedback, if this is specifically for gradle greater than 7 it would be useful to create a new branch to prevent this from occuring.
