### ISSUE TITLE
startNfc() not returning firstname and lastname

### ISSUE THREAD

**Issue by Karan-singh98** [jackbayliss/react-native-nfc-card-reader#22]
the startNfc() is not returning firsname and lastname. It only returns expiryDate, cardNumber and cardType.

**Comment by jackbayliss** [comment]
names should work in this :  [branch ](https://github.com/jackbayliss/react-native-nfc-card-reader/tree/names)

**Comment by yasindemir94** [comment]
i tried for 3 cards and with 2 of them i couldnt get first and last name.

here what i get;

firstName: "java.util.regex.Matcher[pattern=([0-9]{1,19})D([0-9]{4})([0-9]{3})?(.*) region=0,38 lastmatch=5351774593097672D25112262942853500000F]"
lastName:"2942853500000F"

can you help me with that @jackbayliss

**Comment by Karan-singh98** [comment]
> i tried for 3 cards and with 2 of them i couldnt get first and last name.
> 
> here what i get;
> 
> firstName: "java.util.regex.Matcher[pattern=([0-9]{1,19})D([0-9]{4})([0-9]{3})?(.*) region=0,38 lastmatch=5351774593097672D25112262942853500000F]" lastName:"2942853500000F"
> 
> can you help me with that @jackbayliss

I got the similar output
