### ISSUE TITLE
Build errors after installing the package

### ISSUE THREAD

**Issue by EziamakaNV** [jackbayliss/react-native-nfc-card-reader#9]
Hello,

I keep getting build errors after installing the package. I'm not sure what could be wrong. I've followed the installation steps exactly.
The sample code where you showed the implementation works fine.

### Here's the error:

This repository is deprecated and it will be shut down in the future.
See http://developer.android.com/r/tools/jcenter-end-of-service for more information.
Currently detected usages in: project ':react-native-nfc-card-reader'
> Task :app:checkDebugAarMetadata FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
5 actionable tasks: 2 executed, 3 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.github.pro100svitlo:creditCardNfcReader:1.0.3.
     Required by:
         project :app > project :react-native-nfc-card-reader
      > Could not resolve com.github.pro100svitlo:creditCardNfcReader:1.0.3.
         > Could not get resource 'https://www.jitpack.io/com/github/pro100svitlo/creditCardNfcReader/1.0.3/creditCardNfcReader-1.0.3.pom'.
            > Could not HEAD 'https://www.jitpack.io/com/github/pro100svitlo/creditCardNfcReader/1.0.3/creditCardNfcReader-1.0.3.pom'. Received status code 401 from server: Unauthorized

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.github.pro100svitlo:creditCardNfcReader:1.0.3.
     Required by:
         project :app > project :react-native-nfc-card-reader
      > Could not resolve com.github.pro100svitlo:creditCardNfcReader:1.0.3.
         > Could not get resource 'https://www.jitpack.io/com/github/pro100svitlo/creditCardNfcReader/1.0.3/creditCardNfcReader-1.0.3.pom'.
            > Could not HEAD 'https://www.jitpack.io/com/github/pro100svitlo/creditCardNfcReader/1.0.3/creditCardNfcReader-1.0.3.pom'. Received status code 401 from server: Unauthorized

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

**Comment by jackbayliss** [comment]
Hi! It seems the original package I used to build it got pulled- so it’s complaining it can’t find it anymore. 

If I get chance I’ll try to fix it :)

**Comment by jackbayliss** [comment]
@EziamakaNV  Finally updated :)
